live_config_reload = true
import = ["~/.config/alacritty/dracula.toml"]


[window]
decorations = "full"
dynamic_padding = true
opacity = 0.85

[window.padding]
x = 10
y = 10

[scrolling]
history = 10000
multiplier = 3

[font]
size = 10


[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Command"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"
